### ISSUE TITLE
You maybe want to remove the private key here?

### ISSUE THREAD

**Issue by flavens** [ardikabs/eksi-bot#1]
https://github.com/ardikabs/eksi-bot/blob/62570f57bde0e2972f45435d2d9bf4ba780f8765/src/config/serviceAccountKey.json

**Comment by ardikabs** [comment]
Thanks for your suggestion, any idea how i inject that private key from server without uploading in remote repo ? Directly on the server ?

**Comment by flavens** [comment]
You could put it into an environment variable and export the variable into the terminal or your environnement:
`credential: firebaseAdmin.credential.cert(JSON.parse(process.env.FIREBASE_CREDENTIALS))`
and 
` export FIREBASE_CREDENTIALS='{"type": "service_account","p ... }'`

**Comment by ardikabs** [comment]
Thank you sir, i just moved my firebase credentials to env variable.
